my_conf:
  # 健康检查间隔，单位毫秒
  interval: 2000
  # ip port ping超时时间
  pingtimeout: 2000

kubernetes_conf:
  url: https://172.16.0.60:6443
  endpointapi: /api/v1/namespaces/myNameSpaces/endpoints/myEndPoints
  content_type: application/yaml
  # if token_file is none, linux: /var/run/secrets/kubernetes.io/serviceaccount/token(been compiled)
  #                       windows: C:\Users\Administrator\go\my_script\src\lepai.token\token(Not compile)
  # if token_file is 'default', linux and windows: token or conf/token(execute script relative path)
  # or you can specify the token file path
  token_file: C:\Users\Administrator\go\my_script\src\lepai.token\token

# storage conf, one monment only one,if no password or db conf,default is "-"
storage_conf:
  redis:
    ipport: 172.16.0.61:6379
    password:
# healthcheck service args
service_info:
  redis:
    namespace: default
    name: redis
  emqx:
    namespace: default
    name: emqx
  ceph:
    namespace: default
    name: ceph

# healthcheck service target list
service_healthcheck_list:
  redis:
  - port: 38000
  - iplist:
    - name: node-01
      ip: 172.16.0.61
    - name: node-02
      ip: 172.16.0.62
    - name: node-03
      ip: 172.16.0.63
  emqx:
  - port: 6443
  - iplist:
    - name: node-01
      ip: 172.16.0.60
    - name: node-02
      ip: 172.16.0.61
  ceph:
  - port: 38000
  - iplist:
    - name: kid-01
      ip: 172.16.0.61
    - name: kid-02
      ip: 172.16.0.62

# endpoint yaml template，name and namespace will be exchanged
endpoint_template:
  kind: Endpoints
  apiVersion: v1
  metadata:
    name: ceph
    namespace: default
  subsets:
    - addresses:
        - ip: 10.0.0.71
        - ip: 10.0.0.72
      ports:
        - port: 8080
          protocol: TCP